### ISSUE TITLE
Change the tag from pre-alpha to beta

### ISSUE THREAD

**Issue by theredgeek** [carpentries-incubator/lesson-parallel-python#104]
Hello,

I noticed that the tag for this lesson says pre-alpha but the lesson is in the beta stage.

Kind regards and have a great day,
Anne

**Comment by jhidding** [comment]
Hi Anne, thanks for pointing that out! Could you show me where the "tag" is located? I had hoped that changing the setting in `_config.yml` would be enough. Cheers!

**Comment by theredgeek** [comment]
On your right-hand side, under the About section and the link, there are tag-looking topics, and the first one in the second row says pre-alpha. I do not know how to change it, unfortunately. Cheers to you too!

**Comment by tobyhodges** [comment]
@jhidding as an Admin on the repository, you should be able to adjust the tags by clicking a gear wheel/cog button to the right of the _About_ title on [the repository landing page](https://github.com/carpentries-incubator/lesson-parallel-python). Let me know if you need any help.
