### ISSUE TITLE
Add environment (or decribe it)?

### ISSUE THREAD

**Issue by florian-huber** [carpentries-incubator/lesson-parallel-python#13]
Maybe I just missed it, or maybe it is not needed?
But should there be a simple example of how to create a environment for this course?

```
conda create --name parallel_python python=3.8
conda activate parallel_python
conda install dask
pip install numba memory_profiler matplotlib
```

**Comment by florian-huber** [comment]
Maybe also add
```
pip install jupyter
jupyter notebook
```
although that seems a bit basic...
However, for people like me, representing the minority of windows users (that are those that in the course will say that something breaks for them...): I already here ran into kernel error with Jupyter which needed to be fixed by doing
``pip uninstall pywin32`` and then ``conda install pywin32``.

**Comment by jhidding** [comment]
This environment is now available in https://github.com/escience-academy/parallel-python-workshop
