### ISSUE TITLE
Simplify snippet in "The threading module" subsection

### ISSUE THREAD

**Issue by PabRod** [carpentries-incubator/lesson-parallel-python#41]
The code snippet in "the `threading` module" subsection of ["Understanding parallelization in Python"](https://github.com/carpentries-incubator/lesson-parallel-python/edit/gh-pages/_episodes/03-computing-pi.md#L252) has two problems:

- It prints a lot of values, consuming time.
- It uses undefined variables (`input_range` and `ncpus`).

**Comment by isazi** [comment]
I also noticed it reference "calc_pi_numba" that is only defined later in the episode.

**Comment by jhidding** [comment]
Actually the `calc_pi_numba` function is defined in an exercise just before this section; we should make things a bit more xplicit though

**Comment by isazi** [comment]
Okay I did not see the exercise. I could clean the code by defining the undefined variables, and if necessary removing or reducing the print statements (although I like them, at least to show results).
